pub mod claude;
pub mod config;
pub mod display;
pub mod error;
pub mod gh;
pub mod git;
pub mod monitor;
pub mod output;
pub mod progress;
pub mod prompt;
pub mod prompts;
pub mod runner;
pub mod snapshot;
pub mod spec;
pub mod state;

pub use display::{BannerColor, StoryResult};
pub use error::{Autom8Error, Result};
pub use progress::{Breadcrumb, BreadcrumbState, ProgressContext};
pub use runner::Runner;
pub use snapshot::{FileMetadata, SpecSnapshot};
pub use spec::Spec;
pub use state::{MachineState, RunState, RunStatus, StateManager};
